gyasi_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_site.urls")),
    path("management/", include("management.urls")),
    path("user/", include("user.urls")),
    path("payment/", include("payment_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from .views import *

app_name = "management"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("cart/", CategoryView.as_view(), name="category"),
    path("cart-all/", get_categories, name="all_categories"),
    path("change-cart-status/<cart_id>", change_cart_status, name="change_cart_status"),
    path("get-cart-details/<cart_id>", get_cart_details, name="get_cart_details"),
    path("update-cart-details/<cart_id>", update_cart, name="update_cart"),
    path("delete/<cart_id>", delete_cart, name="delete_cart"),
    path("product-list/", ProductListView.as_view(), name="get_product_list"),
    path("product-list/<int:cart_id>", ProductListView.as_view(), name="get_cart_product_list"),
    path("product-details/<int:product_id>", get_product_details, name="get_product_details"),
    path("create-product/", create_product, name="create_product"), # pyright: ignore
    path("update-product/<int:product_id>", update_product, name="update_product"), # pyright: ignore
    path("delete-product/<product_id>", delete_product, name="delete_product"),
    path("delete-image/<image_id>", delete_product_image, name="delete_product_image"),
    path("payments-all/", payment_page, name="all_payments"),
    path("payments/", get_tickets, name="all_sales"),
]

user/urls.py
from django.urls import path, reverse_lazy
from user.views import *

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('admin-login', AdminLoginView.as_view(), name='admin_login'),
    path('user-public-profile', PublicProfileView.as_view(), name='user_public_profile'),
    path('user-public-profile-update', PublicProfileUpdateView.as_view(), name='user_public_profile_update'),
    path('user-public-profile-change-password', ChangePasswordView.as_view(), name='user_public_change_password'),
    path('user-public-profile', PublicProfileView.as_view(), name='user_public_profile'),
    path('register', RegisterUserView.as_view(), name='user_register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate/<token>', verification, name='activate'),
    # path('signup', CreateUserView.as_view(), name='signup-user'),
    # path('signup-invite/<str:slug>/', CreateUserView.as_view(), name='signup-user-invite'),
    # path('verify/<str:token>/<int:user_id>/', verification, name='auth_userx'),
    # path('send-token', send_token, name='send_token'),
    # path('deactivate/<int:user_id>/', deactivate, name='deactivate'),
    # path('profile/<int:id>/change-profile',UploadProfilePictureView.as_view(), name="change-profile"),
]

base/models.py
from django.db import models
import uuid


# with created by field
class BaseModel(models.Model):
    uid = models.UUIDField(editable=False , default=uuid.uuid4, unique=True)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now= True)
    updated_at = models.DateTimeField(auto_now_add= True)

    class Meta:
        abstract = True 

management/models.py
from django.db import models

# Create your models here.

management/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
from main_site.models import Cart, ProductCategoryModel,ProductModel,ProductImageModel, TicketModel
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import date, datetime, timedelta
from django.db.models import Count

class DashboardView(LoginRequiredMixin,View):
    login_url = '/user/admin-login'
    today = date.today()
    currentWeek = date(today.year, today.month, today.day).strftime('%V')
    # for first_day for previous week it will be {int(currentWeek)-1}-1
    first_day_currentWeek= datetime.strptime(f"{today.year}-W{int(currentWeek)}-1", "%Y-W%W-%w").date()
    last_day_currentWeek = first_day_currentWeek + timedelta(days=6.9)
    
    first_day_previousWeek= datetime.strptime(f"{today.year}-W{int(currentWeek)-1}-1", "%Y-W%W-%w").date()
    last_day_previousWeek = first_day_previousWeek + timedelta(days=6.9)
    
    def get(self, request):
        template_name = "management/dashboard.html"

        #today's sales
        tickets = TicketModel.objects.filter(created_at=self.today) #get tickets for today
        ticket_today_sales = sum(ticket.product.ticket_price for ticket in tickets) #pyright:ignore

        #total sales
        tickets = TicketModel.objects.all() #get tickets for today
        ticket_total_sales = sum(ticket.product.ticket_price for ticket in tickets) #pyright:ignore

        #total products
        total_products = ProductModel.objects.all().count() #get total number of products

        # current weekly sales
        tickets = TicketModel.objects.filter(created_at__date__range=[self.first_day_currentWeek,self.last_day_currentWeek])
        current_week_ticket_sales = sum(ticket.product.ticket_price for ticket in tickets) #pyright:ignore

        # previous weekly sales
        tickets = TicketModel.objects.filter(created_at__date__range=[self.first_day_previousWeek,self.last_day_previousWeek])
        previous_week_ticket_sales = sum(ticket.product.ticket_price for ticket in tickets) #pyright:ignore

        # today's orders
        todays_orders = Cart.objects.filter(created_at__date=self.today).count() #get total number of orders

        # total orders
        total_orders = Cart.objects.all().count() #get total number of orders

        # total pending orders
        total_pending_orders = Cart.objects.filter(paid=False).count() #get total number of pending orders

        # total completed orders
        total_completed_orders = Cart.objects.filter(paid=True).count() #get total number of completed orders

        #current week orders
        current_weekly_orders_number = Cart.objects.filter(created_at__date__range=[self.first_day_currentWeek,self.last_day_currentWeek]).count()

        #previous week orders
        previous_weekly_orders_number = Cart.objects.filter(created_at__date__range=[self.first_day_previousWeek,self.last_day_previousWeek]).count()

        #best selling products
        best_selling_products = ProductModel.objects.annotate(count=Count('product_tickets')).order_by('count') #sales based on number of products sold

        best_selling_products_list = []
        for product in best_selling_products:

            # name of product
            product_name = product.name

            # name of product category
            product_category = product.category.name #pyright:ignore

            # owner of product
            product_owner = product.created_by.username #pyright:ignore

            #get number of product orders
            number_of_orders = product.cart_set.all().count() #pyright:ignore

            #get number of completed orders
            number_of_completed_orders = product.cart_set.filter(paid=True).count() #pyright:ignore
            completed_orders = product.cart_set.filter(paid=True) #pyright:ignore

            #get order percentage
            complete_order_percentage = (number_of_completed_orders/number_of_orders) * 100

            #get revenue by product
            product_revenue = sum(i.price for i in completed_orders)

            # revenue percentage of product
            product_revenue_percentage = (product_revenue/ticket_total_sales) * 100

            details = {
                'id':product.id, #pyright:ignore
                'name':product_name,
                'owner':product_owner,
                'category':product_category,
                'number_of_orders':number_of_orders,
                'number_of_completed_orders':number_of_completed_orders,
                'complete_order_percentage':complete_order_percentage,
                'revenue':product_revenue,
                'revenue_percentage':product_revenue_percentage,
            }
            best_selling_products_list.append(details)

        context = {
            'todays_sales': ticket_today_sales,
            'total_sales': ticket_total_sales,
            'total_products': total_products,
            'todays_orders': todays_orders,
            'total_orders': total_orders,
            'current_week_ticket_sales': current_week_ticket_sales,
            'previous_week_ticket_sales': previous_week_ticket_sales,
            'current_weekly_orders_number': current_weekly_orders_number,
            'previous_weekly_orders_number': previous_weekly_orders_number,
            'best_selling_products': best_selling_products_list,
            'total_pending_orders': total_pending_orders,
            'total_completed_orders': total_completed_orders,
        }

        return render(request, template_name, context)


class CategoryView(LoginRequiredMixin,View):
    def get(self, request):
        template_name = "management/categories.html"
        categories = ProductCategoryModel.objects.all()
        context = {'categories':categories}

        return render(request, template_name, context)
    
    def post(self, request):
        name = request.POST.get('cart_name')
        image = request.FILES.get('edit-cart-image')
        new_cart = ProductCategoryModel.objects.create(
            name = name,
            cart_sm_image = image,
            created_by=request.user
        )
        message = "success" if new_cart else ''
        return JsonResponse({'message': message})
    
@login_required
def get_categories(request):
    categories = ProductCategoryModel.objects.all()
    message = 'success'
    cart_list = []
    for cart in categories:
        details = {
            'id': cart.id, # pyright: ignore
            'name': cart.name,
            'created_by': cart.created_by.email, # pyright: ignore
            'cart_class': 'warning' if cart.status == 1 else 'success',
            'cart_txt': "<i title='Deactivate' class='far far fa-times-circle'></i>" if cart.status == 1 else "<i title='Activate' class='far fa-check-circle'></i>",
        }
        cart_list.append(details)
    return JsonResponse({'message': message, 'data': cart_list})

@login_required
def change_cart_status(request, cart_id):
    category = ProductCategoryModel.objects.get(id=cart_id)
    category.status = category.status != True
    category.save()
    return JsonResponse({'message': 'success'})

@login_required
def get_cart_details(request, cart_id):
    cart = ProductCategoryModel.objects.get(id=cart_id)
    details = {
        'id': cart.id, # pyright: ignore
        'name': cart.name,
        'image': cart.cart_sm_image.url if cart.cart_sm_image else '',
        'created_by': cart.created_by.email, # pyright: ignore
    }
    return JsonResponse({'message': 'success', 'details': details})

@login_required
def update_cart(request, cart_id):
    cart = ProductCategoryModel.objects.get(id=cart_id)
    name = request.POST.get('edit-cart-name')
    image = request.FILES.get('edit-cart-image')
    old_image = cart.cart_sm_image
    cart.name = name
    cart.cart_sm_image = image or old_image
    cart.save()
    return JsonResponse({'message': 'success'})
    
@login_required
def delete_cart(request, cart_id):
    category = ProductCategoryModel.objects.get(id=cart_id)
    category.delete()
    return JsonResponse({'message': 'success'})

class ProductListView(LoginRequiredMixin,ListView):
    model = ProductModel
    paginate_by = 6 # number of posts will load
    context_object_name = 'products'
    template_name = 'management/products.html'
    ordering = ['-created_at']
    
    def get_context_data(self,**kwargs):
        context = super(ProductListView,self).get_context_data(**kwargs)
        product_list = []
        products = None
        if self.kwargs.get('cart_id'):
            category = ProductCategoryModel.objects.get(id=self.kwargs.get('cart_id'))
            products = ProductModel.objects.filter(category=category).order_by('-created_at')
            context['category']=category
        else:
            products = ProductModel.objects.all().order_by('-created_at')
        for p in products:
            images = ProductImageModel.objects.filter(product=p)
            details={
                'id': p.id, #pyright: ignore
                'cart_id': p.category.id, #pyright: ignore
                'name': p.name,
                'category': p.category.name,# pyright: ignore
                'image': images[0].image.url if images else '',
                'images': images,
                'ticket_price': p.ticket_price,
                'status': p.status
            }
            product_list.append(details)
        context['products'] = product_list
        return context


@login_required # pyright: ignore
def create_product(request):
    if request.method == "POST":
        images = request.FILES.getlist('product_images')
        category = ProductCategoryModel.objects.get(id=request.POST.get('cart_id'))
        name= request.POST.get('name')
        ticket_price = request.POST.get('ticket_price')

templates/management/products.html
{% extends 'management/base.html' %}
{% load static %}
{% block css %}<link href="{% static 'management/assets/vendors/dropzone/dropzone.min.css' %}" rel="stylesheet" />{% endblock css %}
{% block content %}
<div class="card mb-3">
    <div class="card-body">
      <div class="row flex-between-center">
        <div class="col-sm-auto mb-2 mb-sm-0">
            <button class="btn btn-sm btn-success me-1 mb-0" type="button" type="button" data-bs-toggle="modal" data-bs-target="#new_product_form_modal">+ New</button>
        </div>
        <div class="col-sm-auto mb-2 mb-sm-0">
          {% comment %} <h6 class="mb-0">Showing 1-24 of 205 Products</h6> {% endcomment %}
        </div>
        <div class="col-sm-auto">
          <div class="row gx-2 align-items-center">
            <div class="col-auto">
              <form class="row gx-2">
                <div class="col-auto"><small>Sort by:</small></div>
                <div class="col-auto"> <select class="form-select form-select-sm" aria-label="Bulk actions">
                    <option selected="">Best Match</option>
                    <option value="Refund">Newest</option>
                    <option value="Delete">Price</option>
                  </select></div>
              </form>
            </div>
            {% comment %} <div class="col-auto pe-0"> <a class="text-600 px-1" href="product-list.html" data-bs-toggle="tooltip" data-bs-placement="top" title="Product List"><span class="fas fa-list-ul"></span></a></div> {% endcomment %}
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class="card mb-3">
    <div class="card-body">
      <div class="row infinite-container-products">
        {% for product in products %}
        <div class="mb-4 col-md-6 col-lg-4 infinite-item">
          <div class="border rounded-1 h-100 d-flex flex-column justify-content-between pb-3">
            <div class="overflow-hidden">
              <div class="position-relative rounded-top overflow-hidden" style="height:8cm;">
                <a class="d-block" href="{% url 'management:get_product_details' product.id %}">
                  <img class="img-fluid rounded-top" src="{{product.image}}" alt="" />
                </a>
              </div>
              <div class="p-3">
                <h5 class="fs-0"><a class="text-dark" href="{% url 'management:get_product_details' product.id %}">{{product.name}}</a></h5>
                <p class="fs--1 mb-3"><a class="text-500" href="{% url 'management:get_cart_product_list' product.cart_id %}">{{product.category}}</a></p>
                <h5 class="fs-md-2 text-warning mb-0 d-flex align-items-center mb-3"> ${{product.ticket_price}}</h5>
                <p class="fs--1 mb-1">Stock: <strong class="text-success">{% if product.status %}Available {% else %}Unavailable{% endif %}</strong></p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="card-footer bg-light d-flex justify-content-center">
        <div>
            {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
            {% endif %}
            <div class="d-flex justify-content-center" style="display:none;">
            <i class="fa fa-spinner fa-spin">...loading</i>
            </div>
            {% comment %} <button class="btn btn-falcon-default btn-sm me-2" type="button" disabled="disabled" data-bs-toggle="tooltip" data-bs-placement="top" title="Prev"><span class="fas fa-chevron-left"></span></button>
            <a class="btn btn-sm btn-falcon-default text-primary me-2" href="#!">1</a>
            <a class="btn btn-sm btn-falcon-default me-2" href="#!">2</a>
            <a class="btn btn-sm btn-falcon-default me-2" href="#!"> <span class="fas fa-ellipsis-h"></span></a>
            <a class="btn btn-sm btn-falcon-default me-2" href="#!">35</a>
            <button class="btn btn-falcon-default btn-sm" type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Next"><span class="fas fa-chevron-right"></span></button> {% endcomment %}
        </div>
    </div>
  </div>
  <div class="modal fade" id="new_product_form_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 500px">
      <div class="modal-content position-relative">
        <div class="position-absolute top-0 end-0 mt-2 me-2 z-index-1">
          <button class="btn-close btn btn-sm btn-circle d-flex flex-center transition-base" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body p-0">
          <div class="rounded-top-lg py-3 ps-4 pe-6 bg-light">
            <h4 class="mb-1" id="modalExampleDemoLabel">Create Product</h4>
          </div>
          <div class="p-4 pb-0">
            <form class="dropzone dropzone-multiple p-0" id="my-awesome-dropzone" data-dropzone="data-dropzone" action="{% url 'management:create_product' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3" id="cart_options" data-href="{% if category%}{{category}}{% endif %}">
                  {% if category%}
                  <input type="hidden" value="{{category.id}}" name="cart_id">
                  <h3>Category: {{category.name}}</h3>
                  {% else %}
                  <label for="organizerSingle">Category</label>
                  <select class="form-select js-choice" id="organizerSingle" size="1" name="cart_id" data-options='{"removeItemButton":true,"placeholder":true}'>
                      <option value="">Select Category...</option>
                      {% for cart in all_categories %}
                      <option value="{{cart.id}}">{{cart.name}}</option>
                      {% endfor %}
                  </select> 
                  {% endif %}
                </div>
                <div class="mb-3">
                    <label class="form-label" for="exampleFormControlInputna">Name</label>
                    <input class="form-control" id="exampleFormControlInputna" type="text" name="name" placeholder="Type here..." />
                </div>
                <div class="mb-3">
                  <label class="form-label" for="basic-form-textarea">Description</label>
                  <textarea class="form-control" id="basic-form-textarea" rows="3" placeholder="Description" name="p_description"></textarea>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="exampleFormControlInput1">Ticket Price</label>
                    <input class="form-control" id="exampleFormControlInput1" type="number" name="ticket_price" placeholder="Type here..." />
                </div> 
                <div class="mb-3">
                  <label class="form-label" for="exampleFormControlInput1">Actual Price</label>
                  <input class="form-control" id="exampleFormControlInput1" type="number" name="actual_price" placeholder="Type here..." />
              </div>
                <div class="mb-3">
                    <label class="form-label" for="exampleFormControlInputim">Upload Images</label>
                    <input class="form-control" id="exampleFormControlInputim" type="file" multiple name="product_images"/>
                </div>
                {% comment %} <div class="fallback">
                    <input name="product_images" type="file" multiple="multiple"/>
                </div> {% endcomment %}
                {% comment %} <div class="dz-message" data-dz-message="data-dz-message"> <img class="me-2" src="{% static 'management/assets/img/icons/cloud-upload.svg' %}" width="25" alt="" />Drop your files here</div>
                <div class="dz-preview dz-preview-multiple m-0 d-flex flex-column">
                  <div class="d-flex media mb-3 pb-3 border-bottom btn-reveal-trigger"><img class="dz-image" src="{% static 'management/assets/img/generic/image-file-2.png' %}" alt="..." data-dz-thumbnail="data-dz-thumbnail" />
                    <div class="flex-1 d-flex flex-between-center">
                      <div>
                        <h6 data-dz-name="data-dz-name"></h6>
                        <div class="d-flex align-items-center">
                          <p class="mb-0 fs--1 text-400 lh-1" data-dz-size="data-dz-size"></p>
                          <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress=""></span></div>
                        </div><span class="fs--2 text-danger" data-dz-errormessage="data-dz-errormessage"></span>
                      </div>
                      <div class="dropdown font-sans-serif"><button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal dropdown-caret-none" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-ellipsis-h"></span></button>
                        <div class="dropdown-menu dropdown-menu-end border py-2"><a class="dropdown-item" href="#!" data-dz-remove="data-dz-remove">Remove File</a></div>
                      </div>
                    </div>
                  </div>
                </div> {% endcomment %}
                <div class="modal-footer">
                  <button class="btn btn-primary" id="upload_button" type="submit" data-bs-dismiss="modal">Create</button>
                </div>
            </form>              
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

{% block js %}
<script src="{% static 'management/assets/vendors/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'management/assets/vendors/dropzone/dropzone.min.js' %}"></script>
<script>
    Dropzone.autoDiscover = false;
    $('#my-awesome-dropzone').submit(function (e) {
        e.preventDefault();
        var formData = new FormData(this);
        $('#upload_button').html('<i class="fa fa-spinner fa-spin"></i> Loading...').attr('disabled', true);
        const url = $('#my-awesome-dropzone').attr('action')
        $.ajax({
            url: url,
            type: "POST",
            dateType: "json",
            data: formData,
            processData: false,
            contentType: false,
            success: function (response) {
            if (response.message == 'success') {
                $("#my-awesome-dropzone").trigger("reset")
                $('#upload_button').html('Upload').attr('disabled', false);
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Upload Was Successful',
                    showConfirmButton: true,
                    timer: 2500
                    })
                }
                $(".infinite-container-products").load(location.href + " .infinite-container-products");
            },
            error: function (response) {
                $("#my-awesome-dropzone").trigger("reset")
                $('#upload_button').html('Upload').attr('disabled', false);
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: 'Upload Failed! We will work on it',
                    showConfirmButton: true,
                    timer: 2500
                })
            },
        })
    })

    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container-products')[0],
        handler: function(direction) {
        
        },
        offset: 'bottom-in-view',
        onBeforePageLoad: function () {
        $('.spinner-border').show();
        },
        onAfterPageLoad: function () {
        $('.spinner-border').hide();
        }
      }) 
</script>
{% endblock js %}